config/routes.rb
Rails.application.routes.draw do
  # get 'lists/index'
  # get 'lists/create'
  # get 'lists/new'
  # get 'lists/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check do
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
  delete "bookmarks/:id", to: "bookmarks#destroy"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "This movie already exist in this list" }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list, notice: 'Bookmark was successfully deleted.'
  end
  
  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(set_params)
    if @list.save
      redirect_to list_path(@list) , notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
end

app/helpers/movies_helper.rb
# frozen_string_literal: true

module MoviesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<%= link_to 'Delete', bookmark_path(bookmark), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list,@bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, collection: Movie.all%>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/index.html.erb
<div id="banner-index-list">
  <h1>Save any kind of movies</h1>
</div>
  <div class="container">
    <div class="d-flex justify-content-around">
      <h2 class=" subtitle text-center my-4">My lists</h2>
      <%=link_to "Create a new list", new_list_path, class: "button-create-list my-4"%>
    </div>
  </div>
    <div class="container">
      <ul class="row unordered-list-card">
        <% @lists.each do |list| %>
          <div class="card-list-index col-3 my-4 mx-3">
            <li class="list-unstyled text-center"><%= list.name%></li>
          </div>
        <% end %>
      </ul>
    </div>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

<%= render "form", list: @list %>

app/views/lists/show.html.erb
<h1>Lists#show</h1>


<%= @list.name%>

<% @list.movies.each do |movie| %>
<li><%= movie.title%></li>
<li><%= movie.overview%></li>
<li><%= movie.rating%></li>
<%end%>

<%= link_to "delete this bookmark", list_path(@list), class: "btn btn-danger button-delete fw-bolder", data: { turbo_method: :delete, turbo_confirm:
 "Are you sure you want to delete this list?" } %>

app/views/shared/_navbar.html.erb
<div class="navbar-main">
<%= link_to "My List", lists_path, class:"text-decoration-none fw-normal"%>
<%= link_to "New List", new_list_path, class:"text-decoration-none"%>
</div>